### PR TITLE
add row support (including delete)

### LINKED ISSUE #13: delete_row(idx)
Currently its not possible to remove a row apart from resizing and in this case the row needs to be at the end..

I have a situation where I need to delete a row in the "middle"..

Keep up the good work Anton ;-)))

### PR DESCRIPTION
**Pull request by amleczko**
A very basic row support. Now you can:

``` python
import gspread

# Login with your Google account
gc = gspread.login('thedude@abid.es', 'password')

# Open a worksheet from spreadsheet with one shot
wks = gc.open("Where is the money Lebowski?").sheet1

for row in wks.list_rows():
  # get row value for a given column header, ie. first_name:
  print row.first_name

  # delete a row if it matches your conditions:
  if row.first_name == 'John':
     wks.delete_row(row)
```

This should fix #13

### CODE REVIEW

**Comment by electronicsguy** [comment]
Hi,
   I already have gspread-0.2.5 on my raspberry pi. Is it possible to install your fork side-by-side in a custom directory? I tried setting the **PYTHONPATH** variable and doing this:
```
python setup.py install --home=/home/pi/<custom directory>
```
which copies over the .egg file to the custom directory and creates a .pth file. But when I do:
```
pip freeze
```
It lists this:
gspread==0.2.2amleczko

So it seems to have over-written the original gspread.

**Comment by r00tat** [comment]
@burnash that merge request would be a great enhancement! I'm really missing the delete_row feature right now. Also other people are really looking forward to it (see #186).

**Comment by burnash** [comment]
@r00tat You're right. 
@amleczko I'm sorry for ignoring the pull request for such a long time. 

I'm very short on time though and this PR requires thorough testing. If anyone volunteer to contribute a test suite this will help a lot with merging.

**Comment by jorgelr** [comment]
I would also totally love this function to be merged in.

**Comment by Allard-Timothy** [comment]
This is arguably a very important feature and it seems like it is being ignored. The conflicts being resolved and a merge would help out a lot of people, any progress on this feature would be great!

**Comment by Allard-Timothy** [comment]
+1000 to merging this feature.

**Comment by mehedihasan** [comment]
This pull request has a bug in the delete_row function. It shows up when you try to delete multiple rows. It shows the following error httplib.ResponseNotReady

The fix is quite simple. Change the definition of delete_row function to this.
```python
    def delete_row(self, row_edit_url):
        r = self.session.delete(row_edit_url)
        r.read()
```

I am quite new to git, github, testing and python. So I am not sure how to write the necessary tests and contribute this change along with amleczko's change here. Can anyone please tell me how to do that? Or just point me to somewhere where I can learn.

**Comment by amleczko** [comment]
The branch is now rebased with upstream master.

**Comment by brianwilt** [comment]
if you could merge this, it would make me so happy

**Comment by burnash** [comment]
Thank you again for the contribution. I'm really sorry for the super long pause in the response.

The library has the support of `delete_row()` since #337 

Recently I've ported the library to API v4 which has native support for rows removal.

I'm closing this PR now. Again sorry for the delay in response.

**Pull request closed without merging**
