### PR TITLE
Altered insert_row semantics to utilize range

### PR DESCRIPTION
**Pull request by msuozzo**
This avoids issuing one API request per cell to retrieve the Cell
objects after the insertion row. This provides a significant speed-up
for insertions at the beginning of large sheets.

### CODE REVIEW

**Comment by msuozzo** [comment]
Uhhh. I assume Travis failing isn't normal. Anything I can do to fix that? (Sorry but I've never done this before.)

**Comment by msuozzo** [comment]
I think this also fixes #270

**Comment by burnash** [comment]
Thanks for the PR. Never mind Travis, the set up is still WIP.

**Comment by msuozzo** [comment]
Gotcha.

**Comment by burnash** [comment]
Great work! This is a significant speed-up for the row insertion, indeed.

**Comment by miklevin** [comment]
You guys ROCK! Thanks from a lurking observer who appreciates gold when he sees it.

**Comment by greg-jaunt** [comment]
This change appears to have a serious negative side-effect in that it clears all formulas in the spreadsheet below the insert point.  Is there a way to prevent this?

**Comment by greg-jaunt** [comment]
Looks like my problem is #284.

**Comment by greg-jaunt** [comment]
#284 tracks the issue I'm seeing, which appears to pre-date this patch.  Monkey patching the fix from #338 into gspread 0.4.0 seems to resolve the issue for me.

**Pull request merged**
