### PR TITLE
Add insert_cols method to worksheet

### LINKED ISSUE #798: Inserting columns
I want to insert new columns (between existing columns)

It seems that it's supported by underlying API but not in the provided

I just need inserting empty column, but it's probably makes sense to make the API the same as with insert_row/insert_rows

I'm ready to provide a PR for that if it's fine

### PR DESCRIPTION
**Pull request by AlexeyDmitriev**
Closes #798

### CODE REVIEW

**Comment by AlexeyDmitriev** [comment]
cols is used more often then columns in this class so I went ahead and called it insert_cols, not insert_columns. Let me know if you think that I should rename it.

Also, I think it makes sense to add either add insert_col(umn) or make insert_row deprecated for consistency

**Comment by iisulop** [comment]
Hi,
I would love to get to use this. Is there still something requiring action?

**Comment by burnash** [comment]
Thank you very much for the PR. Yes, I think it makes more sense to deprecate `insert_row()` to remove duplicate functionality.

**Comment by lavigne958** [comment]
closes #576

**Pull request merged**
