### PR TITLE
Fix update_cell on non rect cell list

### PR DESCRIPTION
**Pull request by skaparis**
This fix is for the case then list of cell passed to sheet-update_cell are not top-left conner of upate rect

### CODE REVIEW

**Comment by burnash** [comment]
Thank you for the contribution. Could you please give a more detailed code example of the problem? Could you also add a regression test case?

**Comment by SolusAU** [comment]
```
c1 = Cell(3,1,'ABC')
c2 = Cell(4,2,'ABC')
c3 = Cell(5,3,'DEF')

cell_list = [c3,c1,c2]
wks.update_cells(cell_list)

 'updatedRange': 'rofl_test!A3',
 'updatedRows': 1,
 'updatedColumns': 1,
 'updatedCells': 1}
```

It doesn't create a range based on the minimum and maximum row,cols available.

**Comment by emlazzarin** [comment]
> Thank you for the contribution. Could you please give a more detailed code example of the problem? Could you also add a regression test case?

Right now, the code checks the first cell provided in the `cell_list` to determine the "top-left corner" (minimum value) of the range to-be-updated:

    row_offset = cell_list[0].row
    col_offset = cell_list[0].col

If you ever submit a cell list where the "top-left" cell is not first, this will fail to produce a valid range, and will mangle the sheet.

The submitted diff ensures that the "top-left" (minimum row and minimum column) are used to begin drawing the rectangle-being-updated. Although this may not always be a valid cell, it is always the appropriate point to begin drawing the rectangle-being-updated.

I also checked @SolusAU's example, and it seems to work - nor do I understand the issue they are presenting.

**Comment by hexvolt** [comment]
just merge it, it's been a year, hitting the same issue

**Comment by emlazzarin** [comment]
I would but @burnash hasn't given anyone permission to commit. He's held the repo hostage.

This repo is a great candidate for https://www.codeshelter.co/.

**Comment by hexvolt** [comment]
@emlazzarin yes thanks, that was a message to @burnash :)

**Comment by burnash** [comment]
@skaparis Thank you very much for the fix.

@SolusAU, @emlazzarin thank you for the example and for the detailed explanation.

**Pull request merged**
