### PR TITLE
Add_deprecated_warning_sort_method

### PR DESCRIPTION
**Pull request by lavigne958**
The function signature will change in the coming release 6.0.0

Add a warning for all users.

### CODE REVIEW

**Comment by alifeee** [comment]
This looks good.

The signature will be changed, as per #1090.

A similar warning should be added for #1209?

Merge-time 👍

**Review by alifeee — CHANGES_REQUESTED** [review]
Look good.

`sort(range: str, specs: List[Tuple[int, Union['asc', 'desc']]])` is quite hard to read if you don't use types in python that often.

Might be nice to have a simple "...arguments will swap", or a simple description of the change

**Comment by lavigne958** [comment]
> Look good.
> 
> `sort(range: str, specs: List[Tuple[int, Union['asc', 'desc']]])` is quite hard to read if you don't use types in python that often.
> 
> Might be nice to have a simple "...arguments will swap", or a simple description of the change

that's true, I've been doing python static typing for too long :-p 

I can propose the following method signature (without the types just the arguments names) it's explicit and short: 
`sort(range, specs)` in addition with your comment it should look like:

`This function signature will change, arguments will swap places:  sort(range, specs)`

what do you think ?

**Comment by lavigne958** [comment]
> This looks good.
> 
> The signature will be changed, as per #1090.
> 
> A similar warning should be added for #1209?
> 
> Merge-time +1

yes a similar one will be added very soon, but I put it in a different PR as planned it after this one.

**Comment by alifeee** [comment]
> I can propose the following method signature (without the types just the arguments names) it's explicit and short: `sort(range, specs)` in addition with your comment it should look like:
> 
> `This function signature will change, arguments will swap places: sort(range, specs)`
> 
> what do you think ?

This is good to me 👍

**Comment by lavigne958** [comment]
I updated the message, waiting for you to change your "request for change" to "approve" before merging in case you see anything else.

**Review by alifeee — APPROVED** [review]

**Pull request merged**
