### PR TITLE
Add insert_note feature (#50)

### PR DESCRIPTION
**Pull request by lavigne958**
Closes: #50 
Add the 'insert_note' and 'clear_note' feature.
Notice:
The request to set a note on a cell with an empty string clears the note.
The 'insert_note' function only accepts string as note content

In the test I add I wanted to insert a note and some how through a different process check that the note is inserted but I could not find a way to verify the presence of the note.

I ran a couple of tests myself:
- Insert a note with a text of size 1MiB => works, slow to complete but works
- Over 1GiB text length it times out and an exception is triggered
- I works on _merged_ cells as well

Credits:
Thanks to @archeg that first provided a solution
Thanks to @hexvolt that provided the source code adapted to gpsread

Signed-off-by: Lavigne958 <lavigne958@gmail.com>

### CODE REVIEW

**Comment by lavigne958** [comment]
Before merge, Can someone run the tests suite please ? I tried but I could not run it, I can not figure out the Oauth google service system.... I can connect to my spreadSheets but can not run the test suite with my credentials :-(

**Comment by burnash** [comment]
Sure, I'll run the tests suite before I merge it. Thank you very much for the PR.

**Comment by lavigne958** [comment]
Hi, I managed to run the tests on my machine and it worked, and they all passed, good to go :-)
I mentioned it in a comment in a related Issue: https://github.com/burnash/gspread/issues/737#issuecomment-705132174

**Comment by lavigne958** [comment]
Hi it has been a while isnce this PR is ready. I just give you a heads up in case.

**Comment by burnash** [comment]
@lavigne958 sorry for the pause, looking at it now.

**Comment by burnash** [comment]
Works like a charm. Thank you very much again!

**Comment by billga** [comment]
First off: thanks to burnash for the whole gspread, it's been not only terribly useful, but fun to use. 

Re: lavigne958's question about getting the note...
I'm not sure how to get a note with the gspread spreadsheet object, but I got it with the Google `service` object. There is likely a MUCH easier way to do this, hoping someone can tie this into the gspread model.
```python
from oauth2client.service_account import ServiceAccountCredentials
from googleapiclient import discovery

scope = ['https://spreadsheets.google.com/feeds', 'https://www.googleapis.com/auth/drive']
creds = ServiceAccountCredentials.from_json_keyfile_name(filename, scope)
service = discovery.build('sheets', 'v4', credentials=creds)
```
With that `service` in hand, get the note(s):
```python
fields = 'sheets/data/rowData/values/note'
ranges = [gspread.models.absolute_range_name(sheet.title, "A1")]
request = service.spreadsheets().get(spreadsheetId=sheet.spreadsheet.id, ranges=ranges, fields=fields)
note_json = request.execute()
try:
    note = note_json['sheets'][0]['data'][0]['rowData'][0]['values'][0]['note']  # <-- there's got to be a better way
except KeyError:
    note = None
print(note)
```
I was hoping to incorporate this into the Cell model, so that it could be 'just another field' in the Cell (e.g. `cell.note`). This would make it drop-dead simple to get/set. It looks like maybe passing in the right params to `spreadsheet.values_get()` would work?

**Pull request merged**
