### PR TITLE
add functions for defining, deleting and listing named ranges

### PR DESCRIPTION
**Pull request by p-doyle**
For feature request #833.  Let me know if this looks alright.  I tried running the tests but couldn't get them to work for the 2 tests I added and kept getting 'Requested entity was not found'.  Other than the packages, are there any other requirements for running the tests?

### CODE REVIEW

**Comment by p-doyle** [comment]
Updated the PR, let me know if this works

**Review by lavigne958 — COMMENTED** [review]
thanks for your PR I tested it locally it passes the tests and everything is alright.

I noticed your PR does not pass the linter.
To solve this you can simply run the following command `tox -e format` it will format your code according to the linter.

**Comment by p-doyle** [comment]
Hmm I ran the formatter as part of 0bbba075a0838e20d9c16c6b3fffa94285464878.  I tried running it again from both Windows and Linux and it doesn't change anything.

```
format run-test: commands[0] | black .
All done! ✨ 🍰 ✨
18 files left unchanged.
format run-test: commands[1] | isort --profile black .
Skipped 2 files
```

**Comment by p-doyle** [comment]
Weird, after re-cloning the format worked.  I updated the PR.

**Review by lavigne958 — APPROVED** [review]
LGTM!

**Pull request merged**
