### PR TITLE
remove oauth2client in favor of google-auth, fix #472 and #529

### LINKED ISSUE #472: oauth2client is deprecated, can we use its replacement, google-auth?
### Environment info

Operating System: osx
Python version: 3.6
gspread version: latest

### Steps to reproduce

Oauth2client documentation says it's deprecated and we should be using [google-auth](https://google-auth.readthedocs.io/en/latest/index.html)

If you try to establish credentials with 

```python
credentials = service_account.Credentials.from_service_account_file(
    'service-account.json')

gc = gspread.authorize(credentials)
```

You'll get this error:

```python
Traceback (most recent call last):
  File "spreadsheet.py", line 19, in <module>
    gc = gspread.authorize(credentials)
  File "/usr/local/lib/python3.6/site-packages/gspread/client.py", line 402, in authorize
    client.login()
  File "/usr/local/lib/python3.6/site-packages/gspread/client.py", line 56, in login
    if not self.auth.access_token or \
AttributeError: 'Credentials' object has no attribute 'access_token'
```

Obviously, the google creditials json file doesn't have an 'access_token' key, so something is amiss there.

If I instead use the deprecated 

```python
scope = ['https://spreadsheets.google.com/feeds']
credentials = ServiceAccountCredentials.from_json_keyfile_name('service-account.json', scope)
gc = gspread.authorize(credentials)
```

It works fine.

### PR DESCRIPTION
**Pull request by BigHeadGeorge**
still needs a lotta doc updates tho

### CODE REVIEW

**Comment by BigHeadGeorge** [comment]
not sure why the travis build is failing but it looks like the same tests failing here are also failing in recent commits to master, so i guess it's working now

**Comment by IdlePhysicist** [comment]
Was this ever merged in?

**Comment by burnash** [comment]
@BigHeadGeorge Thank you very much again for your hard work. I'm really sorry for the late response.

**Comment by burnash** [comment]
Backlinking #472 and #529

**Pull request merged**
