### PR TITLE
Update oauth2.rst

### PR DESCRIPTION
**Pull request by londoniscold**
Changed "Desktop" to "Windows UI" as that appears to be a change in the process.

### CODE REVIEW

**Comment by burnash** [comment]
Thank you for the PR. Could you please share more details on why this change is needed?
I don't see any changes related to "Windows UI" in the dropdown in question.


Screenshot 2021-05-03 at 11 20 40

**Comment by londoniscold** [comment]
Ahh, ok, I maybe got waylaid at the wrong step ? I definitely never came across Desktop app in my dropdown, but i managed to make gspread work when I chose Windows UI in my dropdown. I never saw the dropdown you've shown ?

**Comment by burnash** [comment]
Where do you see the dropdown with Windows UI? Maybe you could share the screenshot?

**Comment by burnash** [comment]
The UI of Google Developers Console keeps changing and it is hard to keep track of it.

**Pull request closed without merging**
