### PR TITLE
Allow delete multi rows

### PR DESCRIPTION
**Pull request by deverlex**
Hi, I want to provide function delete multi-rows on sheet

### CODE REVIEW

**Comment by manmartgarc** [comment]
This is a great addition - is this package no longer maintained by @burnash?

**Comment by paulte** [comment]
Is there anything blocking a merge here @burnash, this would massively speed up a number of the use cases I've recently been looking at.

**Comment by burnash** [comment]
Thank you for your contribution and sorry for the late reply.

**Comment by burnash** [comment]
@paulte nothing specific, when the PR arrived, unfortunately, I didn't have too much time to dig into it. Generally, it speeds things up when the description of the PR gives a background on why this addition is necessary _and_ the PR has tests.
I've outlined this in the [contributing guide](https://github.com/burnash/gspread/blob/master/.github/CONTRIBUTING.md) but I understand that it's not always possible for contributors to follow the guide due to time constraints. Hence the delay. Sorry about this.

**Pull request merged**
