### PR TITLE
Improve merge_cells and add merge_type parameter

### PR DESCRIPTION
**Pull request by aiguofer**
Various fixes to the `merge_cells` function including:

- Allowing A1 range name notation
- Fixing tests so it actually tests it works
- Add merge_type parameter

### CODE REVIEW

**Comment by burnash** [comment]
Wow, that was fast! Thank you very much!

**Comment by aiguofer** [comment]
Absolutely :) it's a little easier when I'm bringing over functionality I added to https://github.com/aiguofer/gspread-pandas/

**Comment by burnash** [comment]
@aiguofer Thank you again for the PR. 
You made a lot of very valuable contributions to gspread. Would you be interested in joining gspread as co-maintainer? I've sent you an invitation to the project. If you're not interested that’s totally ok :)

**Comment by lavigne958** [comment]
Nice improvement, if I may advise, in the repository the functions interacting with cells are divided in 2 sets, the first one which accept row/col indexes and the second one with the A1 notation, I believe it brings more clarity if you create a second function that accepts only A1 notation. 

But the test improvement is awesome mate :+1:

**Pull request merged**
