### PR TITLE
fix: fix type annotation for default_blank

### PR DESCRIPTION
**Pull request by hiro-o918**
fix type annotation

### CODE REVIEW

**Comment by lavigne958** [comment]
Hi thank you for contributing, I'm sorry but I don't understand the issue behind your changes.

The input `default_blank` is here to set a value in case of blank cells, when a user wants a specific value. This is typed string so gspread can safely work knowing that all input values are strings.

Could you please explain your changes ?

**Comment by hiro-o918** [comment]
@lavigne958 
Sorry for slow responding.
I found `default_black` passed into [`numericise`](https://github.com/burnash/gspread/blob/60bc77f73501d5d5fe40e6ed179e092c4a759aea/gspread/utils.py#L224) finally.
This seems that the value can accept `Any` value.

For my case, I want to pass [`pd.NA`](https://pandas.pydata.org/docs/reference/api/pandas.NA.html#pandas.NA) as a default value for empty data which is not `str` type.

**Comment by lavigne958** [comment]
> @lavigne958 Sorry for slow responding. I found `default_black` passed into [`numericise`](https://github.com/burnash/gspread/blob/60bc77f73501d5d5fe40e6ed179e092c4a759aea/gspread/utils.py#L224) finally. This seems that the value can accept `Any` value.
> 
> For my case, I want to pass [`pd.NA`](https://pandas.pydata.org/docs/reference/api/pandas.NA.html#pandas.NA) as a default value for empty data which is not `str` type.

I see, this is a different issue then, you request the ability to use a different type and you know the util functions `numericise` will work. though the upper method `get_all_records` will block you from using it.

Then I agree, we need to double check it does not break anything but if this works fine, I'm fine with it.

@alifeee any objection ?

**Comment by alifeee** [comment]
this sounds good to me

only thing to remember is that multiple functions use `default_blank` so they should all be updated

not sure of the need for a test since it's just typing.

**Comment by hiro-o918** [comment]
@lavigne958 @alifeee 
Thank you for your reviews.
I found there is no additional type annotations `str` for `default_blank`
please double check just in case

**Comment by alifeee** [comment]
I think you are correct! Then this is good with me :)

**Review by alifeee — APPROVED** [review]

**Review by lavigne958 — APPROVED** [review]
thank you for this contribution, I checked I found no typing issue. I hope this helps you in the future.

**Pull request merged**
