### PR TITLE
Implement value_render_option on get_all_values per burnash/gspread#612

### PR DESCRIPTION
**Pull request by mklaber**
This PR hopefully addresses #612 sufficiently. A couple things to note:

* I did not add any new tests because there weren't any existing tests for the other methods that have a `value_render_option` parameter
* Some tests are failing but they're the same ones that failed for me from the `master` branch before my changes
* I believe I've added rst comments correctly but am a little new to Python and am unsure how to run Sphinx to test it out

### CODE REVIEW

**Comment by jetlag11235** [comment]
+1 to this PR and the issue it solves.  we were about to implement the same fix.  is it blocked because of the failing tests?  or is there anything we can do to help it cross the finish line?

**Comment by GregOwen** [comment]
+1 to this PR; I would love to use this feature. It looks like many of the tests are failing with a 401 error (seems like the test credentials may be bad?), but there does seem to be a legitimate failure in `SpreadsheetTest.test_values_get`. @motin are you still interested in working on this or have you moved on?

**Comment by burnash** [comment]
Thank you for your contribution, @mklaber and sorry for the late response.

**Comment by HolabeFelixBecker** [comment]
Hi guys, 
i have a problem using this function :(

This is my example code (Google Colab):
```
gc = gspread.authorize(GoogleCredentials.get_application_default())
wb = gc.open_by_url('link to spreadsheet')
ws = wb.worksheet('Sheet1')
data = ws.get_all_values(value_render_option='Formula')
```

Error:
`get_all_values() got an unexpected keyword argument 'value_render_option'`

Would be great if sb could tell me how to use this function.

**Comment by burnash** [comment]
@HolabeFelixBecker please check the documentation of [get_all_values()](https://gspread.readthedocs.io/en/latest/api.html#gspread.models.Worksheet.get_all_values)

**Comment by HolabeFelixBecker** [comment]
Hi @burnash, 
thank you for the quick answer. I could not find this function in the documentation hence I am here. I tried value_render_option="FORMULA" and it is not working. 
I checked the source code and tried to understand the function:

I also tried:

`ws.spreadsheet.values_get('A1:B1', value_render_option='FORMATTED_VALUE')`

this is also not working for me

**Comment by burnash** [comment]
@HolabeFelixBecker I would suggest upgrading gspread and trying again.

**Comment by HolabeFelixBecker** [comment]
Thank you - this was the problem. I have not figured out how to force update in google colab (not working via pip for some reason) - I uploaded the models.py manually into:
/usr/local/lib/python3.6/dist-packages/gspread/models.py

I will look into updating the package and post a solution later.
Thanks for all the help

**Comment by burnash** [comment]
@HolabeFelixBecker here's the example from the official colab notebooks: 
https://colab.research.google.com/notebooks/io.ipynb#scrollTo=sOm9PFrT8mGG

**Pull request merged**
