### PR TITLE
update readme examples

### LINKED ISSUE #1410: Update examples of gspread usage /Readme.md
Hi, 

Their is no usage example of single cell update in the Read me as the example currently is not complete . 
simple add worksheet.update_acell('A1', 'Bingo!') to the updating cell example

### PR DESCRIPTION
**Pull request by alifeee**
closes #1410 

The examples in the readme were wrong, and did not work

I think we should go through and test them to see if they work. I will do this soon if you do not. :)

### CODE REVIEW

**Comment by lavigne958** [comment]
> closes #1410
> 
> The examples in the readme were wrong, and did not work
> 
> I think we should go through and test them to see if they work. I will do this soon if you do not. :)

I will test them now

**Comment by lavigne958** [comment]
The below example don't work either:

- https://github.com/burnash/gspread/blob/20005407e46c9c637ebb1ad6c5345e82d27593f1/README.md?plain=1#L264
   we should swap the value and the range too, and put the value into a matrix `[[".."]]`

apart from that the rest works fine :+1:

**Comment by alifeee** [comment]
re: https://github.com/burnash/gspread/issues/1410#issuecomment-1986206623, I may have got the examples here the wrong way round. not sure. have to test.

**Review by lavigne958 — APPROVED** [review]

**Comment by lavigne958** [comment]
> re: [#1410 (comment)](https://github.com/burnash/gspread/issues/1410#issuecomment-1986206623), I may have got the examples here the wrong way round. not sure. have to test.

looks good, I checked it's the right way around now.

**Pull request merged**
