### PR TITLE
Update numericise with underscores test to work in python2 and <python3.6

### PR DESCRIPTION
**Pull request by epicfaace**
Otherwise, that single test is failing in Travis.

### CODE REVIEW

**Comment by epicfaace** [comment]
@burnash , can you merge this PR so that the tests will pass?

**Comment by epicfaace** [comment]
@burnash -- just a reminder.

**Comment by lavigne958** [comment]
It has been a long time since that PR is here, and it seems to very usefull for all the tests to pass.

@burnash it would help all of us making this library even better than it already is if you could merge that PR please.

**Comment by burnash** [comment]
Thank you very much for the fix. My apologies for the slow reply.

**Pull request merged**
