### PR TITLE
Improve back-off client

### LINKED ISSUE #1268: Fix BackOffHTTPClient not returning error 403
Currently, we cannot reliably test raising of `PermissionError` (see #1244 #1245).

This is because for the tests, a [`BackOffHTTPClient`] is used, which has problems returning 403 errors.

https://github.com/burnash/gspread/blob/6259c2be9fae8e7567ea1796dd98e3c0d2570672/gspread/http_client.py#L329-L335

https://github.com/burnash/gspread/blob/6259c2be9fae8e7567ea1796dd98e3c0d2570672/tests/client_test.py#L110-L127

[`BackOffHTTPClient`]: https://github.com/burnash/gspread/blob/6259c2be9fae8e7567ea1796dd98e3c0d2570672/gspread/http_client.py#L310

If this is fixed, the test can be un-skipped.

With the normal HTTP client, it works fine (returns `PermissionError` immediately)

### LINKED ISSUE #1326: May be able to exclude 403 Forbidden from Backoff HTTP codes
https://github.com/burnash/gspread/blob/0a2f084a192ba8038900891c2d1c441cfa10d611/gspread/client.py#L603

Greetings,

I don't see where in the google API docs it states that `403` is also used for exceeding the request limits, seems like they have a specific status code for this (`429`). I believe this status code can be safely removed from the list in the backoff client to allow for immediate exceptions in cases of access related issues.

### PR DESCRIPTION
**Pull request by lavigne958**
Catch usage limit errors from the Drive API. it returns the HTTP code 403 (access denied) on usage limits and access denied. Find the difference in both case and retry when it's usage limits exceeded.

Improve back-off client code.

Add pretty print for the APIerror Exception.

closes #1268
closes #1326

### CODE REVIEW

**Comment by alifeee** [comment]
these changes look good to me. two things:

- the test in #1268 needs to be un-skipped, or the issue is not closed
- we should add a test with this new functionality.

**Comment by lavigne958** [comment]
> these changes look good to me. two things:
> 
> * the test in [Fix BackOffHTTPClient not returning error 403 #1268](https://github.com/burnash/gspread/issues/1268) needs to be un-skipped, or the issue is not closed
> * we should add a test with this new functionality.

I enabled the previously skipped test.

I am not sure how to test this new code, we have a test that tries to open a forbidden spreadsheet.
We can't make a test that reaches the limits of the quotas by sending many requests: as this will take forever to record the first time and everytime we update the cassettes. last time I ran this code I could not reach the limit of quota due to the backoff client :face_with_spiral_eyes:

**Comment by alifeee** [comment]
Can we mock the requests object for just this one test? Instead of using cassettes, we could mock requests to return 419 (or the right HTTP #), and then test that the client works as expected (likely by setting the timeout very low so it only retries once or twice)

**Comment by lavigne958** [comment]
> Can we mock the requests object for just this one test? Instead of using cassettes, we could mock requests to return 419 (or the right HTTP #), and then test that the client works as expected (likely by setting the timeout very low so it only retries once or twice)

I ran some tests and I can't figure it out, I can change requests before they are made but they still need to be made, I can filter/change responses before they are returned to us but requests still need to be made with a valid response.

I can't find a way to filter that request specifically and change it's return code, in a some _easy/simple_ ways.

it looks like a lot of work for a automatic test. 

is it ok for you if we keep it like this for now ?

**Review by alifeee — APPROVED** [review]
> is it ok for you if we keep it like this for now ?

yes :) I think people will probably not hit the rate limit enough that it is *that* important...

**Comment by lavigne958** [comment]
> > is it ok for you if we keep it like this for now ?
> 
> yes :) I think people will probably not hit the rate limit enough that it is _that_ important...

thank you, I agree, I tried it myself... :laughing:  never reached it

**Pull request merged**
