### PR TITLE
Fixed default value of merge_type parameter in merge_cells function docstring.

### PR DESCRIPTION
**Pull request by neolooong**
Fixed default value of merge_type parameter in merge_cells function docstring.

### CODE REVIEW

**Comment by alifeee** [comment]
thanks, this is helpful! I always love a docs change :)

got me thinking, why aren't we using a tuple for this parameter? like for `DateTimeOption`?

https://github.com/burnash/gspread/blob/c3b61d0571bfc87a04fbbfe4e1cbcf6e2487fb6e/gspread/utils.py#L41-L43

perhaps we could change it... @lavigne958 thoughts ?

**Comment by lavigne958** [comment]
Thanks for the doc update.

I think we missed it 😮
Yep we can upgrade it to a namedtuple but we should make sure people can keep using strings and it works. That I'm not sure 😬 if that does not work we can't change it and should just update the documentation

**Comment by neolooong** [comment]
I am sure that after changing to namedtuple, people still can use string.

**Comment by alifeee** [comment]
quick change! it looks good :)

now is probably also the time to add a test for `merge_cells` (and a `merge_type` test too), since there is not one in [`worksheet_test.py`](https://github.com/burnash/gspread/blob/master/tests/worksheet_test.py)

you are welcome to give this a go, or one of us will do it if you would rather not deal with the tests :)

**Review by lavigne958 — APPROVED** [review]
thanks for the fix ! 
I agree if you feel like it, feel free to add a test on merge cells, if not, no worries we'll add them.

Tested it, it works in all bellow cases:
- with `sheet.merge_cell("A1:B2", "MERGE_ALL")`
- with `sheet.merge_cell("A1:B2", gspread.utils.MergeType.merge_all)`
which makes it ISO functional with current code base :+1:

**Comment by alifeee** [comment]
super. we will merge this and add a test for `merge_cells` in a week or so if there is no more activity here :)

**Review by lavigne958 — APPROVED** [review]
Thanks for the new tests !

**Pull request merged**
