### PR TITLE
merge read the doc configuration file from master

### PR DESCRIPTION
**Pull request by alifeee**
(cherry picked from commit a659f88c9bfdd080ee4f30ca95b30ca94aeb7f6f)

this way we will not have to remember to update sphinx dependency, but it will be updated from the get-go

### CODE REVIEW

**Comment by alifeee** [comment]
I also make this instead of waiting for @dependabot, because it is the last item in #1214 so we can close that after.

**Comment by lavigne958** [comment]
Hey that's a good idea to update that branch too. 

To le we should simply merge master branch into feature/6.0.0 that way we keep them both on track and the feature brench receives everything like the update on the license etc.

**Comment by alifeee** [comment]
> we should simply merge master branch into feature/6.0.0

I did not do this because it would not be simple. Many merge conflicts since `master` has changed a fair amount from when `6.0.0` was forked off it.

However, the changes must be made eventually. However however, does it make more sense to merge `6.0.0` branch into `master` rather than the other way round? (and naturally we would do this later on, when the `6.0.0` release is imminent)

**Comment by lavigne958** [comment]
you should not have too many changes to apply. I tend to merge master branch from time to time into `6.0.0`. 

I'll make a PR with the integration of the latest changes in `master` into `6.0.0`.

It makes sense as you mention it the day we actually release the version `6.0.0`. before that both branches will live their life along side each others. with the detail that `6.0.0` will receive all new changes from time time.

**Comment by lavigne958** [comment]
Done in #1241 
We can close this PR.

**Pull request closed without merging**
