### PR TITLE
Add auth.service_account_from_dict

### LINKED ISSUE #784: Add service_account from dict
**Is your feature request related to a problem? Please describe.**
There's an option for loading config from dict, like from file

**Describe the solution you'd like**
There's already `service_account`, I think, we can add something like `service_account_from_dict`
So, `ServiceAccountCredentials.from_service_account_file` is used for `service_account`. And we can create `service_account_from_dict` for utilizing `ServiceAccountCredentials.from_service_account_info`

**Describe alternatives you've considered**
Another way is to write more code

### PR DESCRIPTION
**Pull request by mahenzon**
Closes #784

### CODE REVIEW

**Comment by burnash** [comment]
This is excellent. Thank you very much, I'll review it shortly.

**Comment by burnash** [comment]
Looks great, thank you very much again!

**Comment by am1ru1** [comment]
@mahenzon : 

`import gspread`

```
----> 7 gc = gspread.service_account_from_dict(base64.b64decode(acc))
      8 


AttributeError: module 'gspread' has no attribute 'service_account_from_dict'
```

I have install directly from the pull 785, but unable to call the function. Am I missing something here?

**Comment by mahenzon** [comment]
Hi @am1ru1 !
Are you sure you've installed the latest version?

Works for me:
- Installing from github commit: `git+https://github.com/burnash/gspread#50c9edb6880e05face99ed2d30f8f73afdfd5ad8`:

```
(venv)  ~/projs  pip install git+https://github.com/burnash/gspread#50c9edb6880e05face99ed2d30f8f73afdfd5ad8
Collecting git+https://github.com/burnash/gspread#50c9edb6880e05face99ed2d30f8f73afdfd5ad8
  Cloning https://github.com/burnash/gspread to /tmp/pip-req-build-qz55l5ed
Requirement already satisfied (use --upgrade to upgrade): gspread==3.6.0 from git+https://github.com/burnash/gspread#50c9edb6880e05face99ed2d30f8f73afdfd5ad8 in ./venv/lib/python3.6/site-packages
Requirement already satisfied: requests>=2.2.1 in ./venv/lib/python3.6/site-packages (from gspread==3.6.0) (2.24.0)
Requirement already satisfied: google-auth>=1.12.0 in ./venv/lib/python3.6/site-packages (from gspread==3.6.0) (1.19.0)
Requirement already satisfied: google-auth-oauthlib>=0.4.1 in ./venv/lib/python3.6/site-packages (from gspread==3.6.0) (0.4.1)
Requirement already satisfied: idna<3,>=2.5 in ./venv/lib/python3.6/site-packages (from requests>=2.2.1->gspread==3.6.0) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.6/site-packages (from requests>=2.2.1->gspread==3.6.0) (2020.6.20)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./venv/lib/python3.6/site-packages (from requests>=2.2.1->gspread==3.6.0) (1.25.9)
Requirement already satisfied: chardet<4,>=3.0.2 in ./venv/lib/python3.6/site-packages (from requests>=2.2.1->gspread==3.6.0) (3.0.4)
Requirement already satisfied: six>=1.9.0 in ./venv/lib/python3.6/site-packages (from google-auth>=1.12.0->gspread==3.6.0) (1.15.0)
Requirement already satisfied: setuptools>=40.3.0 in ./venv/lib/python3.6/site-packages (from google-auth>=1.12.0->gspread==3.6.0) (40.6.2)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in ./venv/lib/python3.6/site-packages (from google-auth>=1.12.0->gspread==3.6.0) (4.1.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in ./venv/lib/python3.6/site-packages (from google-auth>=1.12.0->gspread==3.6.0) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4; python_version >= "3" in ./venv/lib/python3.6/site-packages (from google-auth>=1.12.0->gspread==3.6.0) (4.6)
Requirement already satisfied: requests-oauthlib>=0.7.0 in ./venv/lib/python3.6/site-packages (from google-auth-oauthlib>=0.4.1->gspread==3.6.0) (1.3.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in ./venv/lib/python3.6/site-packages (from pyasn1-modules>=0.2.1->google-auth>=1.12.0->gspread==3.6.0) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in ./venv/lib/python3.6/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread==3.6.0) (3.1.0)
You are using pip version 18.1, however version 20.2b1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

- And then running

```python
(venv)  ~/projs  python
Python 3.6.9rc1+ (heads/3.6:a1093e4, Jun 30 2019, 16:02:40) 
[GCC 7.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from gspread import service_account_from_dict
>>> print(service_account_from_dict.__doc__)
Authenticate using a service account (json).

    ``scopes`` parameter defaults to read/write scope available in
    ``gspread.auth.DEFAULT_SCOPES``. It's read/write for Sheets
    and Drive API::

        DEFAULT_SCOPES =[
            'https://www.googleapis.com/auth/spreadsheets',
            'https://www.googleapis.com/auth/drive'
        ]

    You can also use ``gspread.auth.READONLY_SCOPES`` for read only access.
    Obviously any method of ``gspread`` that updates a spreadsheet
    **will not work** in this case.

    :param info (Mapping[str, str]): The service account info in Google format
    :param list scopes: The scopes used to obtain authorization.

    :rtype: :class:`gspread.Client`
    
>>> 
```

**Comment by am1ru1** [comment]
@mahenzon I thought I did a correct pull earlier but now with the commit pull it is working. 
Muchos gracias!

**Comment by HassanJaveed84** [comment]
@burnash I was hoping to use `service_account_from_dict`. Do you know when this would make into a release ?

**Pull request merged**
