### PR TITLE
Add with_link attribute for sharing

### PR DESCRIPTION
**Pull request by epicfaace**
This way, one can share a spreadsheet only if people have the link, for example.

### CODE REVIEW

**Comment by burnash** [comment]
This looks like a duplicate of #621
Closing.

**Comment by epicfaace** [comment]
@burnash oops -- the PR description / name was duplicate, but the actual code change was different -- I've just updated the PR name / description to accurately reflect the change I made.

**Comment by burnash** [comment]
@epicfaace Thank you for the clarification, in this case, I believe, it got merged in #622 isn't it?

**Comment by epicfaace** [comment]
@burnash yeah, you're right -- must have just made this PR by accident then! Thanks

**Pull request closed without merging**
