### PR TITLE
Updated get_all_values (deprecated) method to get_values in README

### PR DESCRIPTION
**Pull request by RodrigoTomeES**
Updated get_all_values (deprecated) method to get_values

### CODE REVIEW

**Review by lavigne958 — APPROVED** [review]

**Comment by lavigne958** [comment]
Thank you @RodrigoTomeES  for this small but useful fix :slightly_smiling_face:

**Comment by RodrigoTomeES** [comment]
@lavigne958 Thanks to you for gspread! You have done a great job

**Comment by lavigne958** [comment]
ha ha thanks but I can't take all the credit to myself. I just got involved very recently, @burnash made all the hard work for the past years, with the help of @aiguofer  and @msuozzo :wink:

**Comment by RodrigoTomeES** [comment]
Thanks to all of them too hahaha

**Pull request merged**
