### PR TITLE
#1104: added a delete by worksheet id method

### LINKED ISSUE #1104: del_worksheet doesn't translate the name to id
worksheet = sh.del_worksheet(value from variable holding the name of the worksheet)

error:
```
/lib/python3.8/site-packages/gspread/spreadsheet.py", line 436, in del_worksheet
    body = {"requests": [{"deleteSheet": {"sheetId": worksheet.id}}]}
AttributeError: 'str' object has no attribute 'id'
```
**To Reproduce**
```
worksheet_name = 'something'
* sh = gc.open_by_url('https://docs.google.com/spreadsheets/d/<hash>')
* worksheet = sh.del_worksheet(worksheet_name)
```
**Expected behavior**
spreadsheet.py should either obtain id if required, or documentation should specify the requirement of obtaining an id

**Environment info:**
- Operating System: Ubuntu in WSL
- Python version: Python 3.8.10
- gspread version is: 5.4.0

### PR DESCRIPTION
**Pull request by muddi900**
Closes #1104

Added a delete by Worksheet Id method in the Spreadsheet Class

### CODE REVIEW

**Comment by lavigne958** [comment]
Hi, thank you for your contribution.

I need to check what is this new vulnerability and how we can solve it.

Until then unfortunately we can't merge your PR 😔

**Comment by muddi900** [comment]
I understand

**Comment by lavigne958** [comment]
Hello the CI has been fixed, you should now be able to merge your PR, could you please rebase it onto the master branch ?

**Review by lavigne958 — APPROVED** [review]
thank you for your contribution, looks good to me.

**Pull request merged**
