### PR TITLE
Support cell formats (using v4 JSON API)

### PR DESCRIPTION
**Pull request by robin900**
Fixes burnash/gspread#531.

Supports all basic formatting directives for cells, via new `format_range()` method on Worksheet.

I've included full test coverage of the added method and property accessors. And a section added to README.

### CODE REVIEW

**Comment by robin900** [comment]
@burnash I'm happy to provide integration test coverage (live tests of a google sheet using the tests.config thing) if you could provide a small amount of guidance on how best to write those tests.

**Comment by robin900** [comment]
@burnash I've added test coverage for `format_range` method. To accomplish the test, I've allowed passing of `params` to `Spreadsheet.fetch_sheet_metadata`, in a backward-compatible way, so that one can ask for certain data ranges to be included in the metadata. (That's the only way that v4 Sheets API allows for fetching the `userEnteredFormat` or `effectiveFormat` of any given cell.)

**Comment by robin900** [comment]
@burnash I'm wondering if you'd like this cell formatting functionality to be included in gspread, or if perhaps I should create a new PyPI package, `gspread-formatting`, that provides the same functionality as in this PR. 

I think this functionality is better suited to being in `gspread` itself; the PR includes sufficient test coverage of the new `format_range` method, the new arguments added to `resize`, and the new property accessors, including read accessor for `default_format`.

**Comment by robin900** [comment]
@burnash I imagine you're very busy! This PR has ample integration test coverage which passes when using my own Sheets API credentials, so I'd like to recommend the PR for review and approval at the earliest opportunity.

The TravisCI failures are happening to all branches, not just this PR, because the API credentials/project configured for the CI build always hits the API call limit during the test suite's execution. I asked for and received an increase in the API call limit for my own API credentials/project, and then the test suite (on master and for my PR) completes without any errors or failures. I recommend making the same API limit increase request to Google for the credentials/project used in TravisCI.

I'd really like to get this PR merged and into a PyPI release -- then other teams in my organization will be able to use the cell formatting support. These other teams (understandably) don't want to source any packages from a git: url or custom pypi server I provide. So I'd really like to see this PR get into an official PyPI release of `gspread`.

Thanks for any attention you can provide, and thanks for developing a great package. My team relies on `gspread` for a lot of our data processing and analysis workflows.

**Comment by robin900** [comment]
@burnash any chance to review this PR?

**Comment by burnash** [comment]
@robin900 Thank you for the contribution. I'm really sorry for not responding. 
This is true: I'm overwhelmed at my day job currently and when I get a chance to check gspread I prioritize bugfixes over new features.

I think cell formatting is really needed and it's a great feature to add to gspread. I'll try to review the proposed API and get back to you asap.

**Comment by vikasbhatia** [comment]
Hi @robin900 and @burnash, I'm working on a project where I need to read a cell's formatting from a Google sheet in Python, specifically the background colour. As far as I can see this PR allows you to set formatting, but not get. This [open issue](https://github.com/nithinmurali/pygsheets/issues/186) on pygsheets' (another alternate I tried) GitHub page describes the kind of functionality I need. Is this possible? Thank you so much for everything!

**Comment by robin900** [comment]
@vikasbhatia This PR already offers one feature related to reading formats from a sheet: reading the defaultFormat for the entire spreadsheet:

https://github.com/burnash/gspread/pull/546/files#diff-78d0f1e3c86227021e89498ae6879c41R70

CellFormat objects as defined in this PR are mutable and can then be used with the `format_cells()` method to apply changes in formatting.

When it comes to reading the "effective format" or "user entered format" for any particular cell or cell range, I don't know if I understand what the best or most common practice is to retrieve and use this information for Sheets v4 API. I'm also unclear on how best to associate a cell format with the cell value or cell identity. But I'm happy to try to add support for easy format retrieval in a subsequent PR.

**Comment by vikasbhatia** [comment]
That’d be fantastic @robin900, thank you. This is very easy to do with Apps Script with [getBackground()](https://developers.google.com/apps-script/reference/spreadsheet/range#getBackground()) so I found it a bit disappointing that I couldn’t find a straightforward way to do this with the API. I tried diving into Google’s own client library, but the docs aren’t the easiest thing to read. If it helps you at all, someone on StackOverflow pointed me to this:

spreadsheets.get, request the appropriate fields. Note that the Python API Explorer can be extremely helpful: developers.google.com/apis-explorer/#p/sheets/v4/… (it has an interactive and explanatory fields selector!)

Thank you again for all your work.

**Comment by robin900** [comment]
@burnash This PR has, I believe, more than adequate test coverage. The entire (expanded) test suite succeeds using my own Google credentials. I've just added (with test coverage) support for equality testing, add/+, difference/-, and intersection/& operations on CellFormat objects, which have really helped in my real-world use cases of cell formatting.

If you want to get the TravisCI builds to start passing again, I recommend asking Google to increase the API limit for your account. A quick note explaining that you maintain `gspread` should be enough for them to bump your API limit to something that can easily accommodate dozens of TravisCI runs of the test suite each day.

**Comment by robin900** [comment]
@burnash -- sorry, about the TravisCI build, I was meaning that you could switch over the CI build to use the live, integration tests rather than the (still v3-based) mock_tests.

**Comment by robin900** [comment]
@vikasbhatia I added `get_effective_format(label)` and `get_user_entered_format(label)` to this PR.

Note that if you want to do more advanced fetching of format data, such as for a whole range, you can use the lower-level `Spreadsheet.fetch_sheet_metadata` method to do something like this:

```
from gspread.format import CellFormat

wksht = some_worksheet_you_have
range = '%s!A1:D200' % wksht.title
resp = wksht.spreadsheet.fetch_sheet_metadata(
    {
    'includeGridData': True, 
    'ranges': [range], 
    'fields': 'sheets.data.rowData.values.userEnteredFormat'
    }
)
for value in resp['sheets'][0]['data'][0]['rowData'][0]['values']:
    fmt = CellFormat.from_props(value['userEnteredFormat'])
    # do something with fmt...
```

**Comment by robin900** [comment]
@burnash In a now-separate branch, I managed to get all the TravisCI and test config/creds issues worked out, but only of course for my forked repo and not burnash/gspread. 

So I've moved all that Travis stuff to a new branch and this PR here now has only code that adds the cell-formatting support. It's still possible to test this branch locally if you set up `tests.config` properly. I'm seeing all tests pass locally for this PR.

**Comment by vikasbhatia** [comment]
@robin900 excellent, thanks! I’ll be able to try this in a little over a day’s time; I’ll follow up on it then.

**Comment by matiasrivera** [comment]
Hi @robin900 is there any way of getting your cell format code and add it to my current gspread installation?

**Comment by robin900** [comment]
@matiasrivera @vikasbhatia I've uploaded a new PyPI package, `gspread-formatting`, with all of the functionality of this PR _except for_ frozen_rows and frozen_cols. I really think this functionality belongs in gspread itself, but I wanted you guys to have this code so you can make progress on your projects and give me some feedback on how the code works for you:

https://pypi.org/project/gspread-formatting/

**Comment by matiasrivera** [comment]
@robin900 thanks for this. It seems that you have color codes backwards. For example to get the color (red=205, green=19, blue=19) I have to enter 255 minus the desired value to get it correct
backgroundColor=Color(red=50, green=236, blue=236,alpha=1), in order to get what I expect

**Comment by robin900** [comment]
@matiasrivera No, it's the Google Sheets API's Color element that differs from your expectations:

https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets#Color

Each value is a fraction of 255: 1.0 means 255, 0.5 means ~ 128, etc.

**Comment by vikasbhatia** [comment]
Hey @robin900, first off my apologies for responding so late, had too many things going on. For my project, I just wanted to check whether certain cells had a red background or not, and do something based on that. I'm happy to report that it's working!

Using `gspread` + your `gspread-formatting` PyPi package, I made the background of a cell (`B14`) red and then ran `print(get_effective_format(worksheet, "B14"))`. This returned `backgroundColor=(red=1);padding=(top=2;right=3;bottom=2;left=3);horizontalAlignment=LEFT;verticalAlignment=BOTTOM;wrapStrategy=OVERFLOW_CELL;textFormat=(foregroundColor=();fontFamily=arial,sans,sans-serif;fontSize=10;bold=False;italic=False;strikethrough=False;underline=False);hyperlinkDisplayType=PLAIN_TEXT`

So I was able to use `if get_effective_format(worksheet, username_cell).backgroundColor.red != 1:` to do my job. Now my only concern is the runtime. Will it make any difference if I use `get_user_entered_format` instead of `get_effective_format`? I'm using `worksheet.findall` to find rows that match a specific search query, and then looping through the results to check which ones are marked red. This is taking about 12 seconds to find 2 records out of 16 in the sheet, and from my testing it's the formatting check which is taking up time.

`get_effective_format(worksheet, username_cell).backgroundColor.red` always returns a red object, while `get_user_entered_format(worksheet, username_cell).backgroundColor.red` does not. So if I switch, I'll have to account for a NoneType error if I use `get_user_entered_format`.

**Comment by matiasrivera** [comment]
@robin900 Thanks for the clarification. One thing I believe would be nice to have is to be able to update the cell's format as well as the value in the same call. Do you think it could be possible to  extend gspread's current update_cells function and be able to set the Cells format in gspread's cell object? Otherwise I have to make two calls one to update the cell's value and a second one to update it's format.

**Comment by robin900** [comment]
@matiasrivera Updating the value _and_ the format in one call is, of course, a lovely idea; but to implement, we will need to discuss and devise the best way to design this functionality for the gspread user. Also, you should note that the Sheets API itself does not offer an easy and fast way to update both values and format for a range of cells -- you're either posting a list of values only, or doing a `repeatCell` operation with just formatting. Adding your desired feature won't be a quick programming job!

**Comment by robin900** [comment]
@vikasbhatia sorry about that, try: `eff_fmt.backgroundColor = color(red=1)`

**Comment by vikasbhatia** [comment]
@robin900 confirmed, that worked. I was using a workaround to get functional code earlier, but this will help me clean it up a bit. Thank you so much again for not only taking the time to respond, but for really going the extra mile on someone's random request. I sincerely appreciate it!

**Comment by Bigardi** [comment]
@robin900 When i try: print(get_effective_format(worksheet, "B9") 
this error occurs:

Traceback (most recent call last):
  File "/home/bigardi/PycharmProjects/ganesha/testes/googledrive.py", line 83, in planilhas
    print(get_effective_format(worksheet, "B9"))
  File "/usr/local/lib/python3.6/dist-packages/gspread_formatting.py", line 66, in get_effective_format
    return CellFormat.from_props(props) if props else None
  File "/usr/local/lib/python3.6/dist-packages/gspread_formatting.py", line 215, in from_props
    return _props_to_component(_underlower(cls.__name__), props)
  File "/usr/local/lib/python3.6/dist-packages/gspread_formatting.py", line 180, in _props_to_component
    v = _props_to_component(k, v)
  File "/usr/local/lib/python3.6/dist-packages/gspread_formatting.py", line 180, in _props_to_component
    v = _props_to_component(k, v)
  File "/usr/local/lib/python3.6/dist-packages/gspread_formatting.py", line 176, in _props_to_component
    raise ValueError("No format component named '%s'" % class_alias)
ValueError: No format component named 'bottom'

can u help me?

**Comment by burnash** [comment]
@robin900 Thank you very much again for your contribution. I apologize for the delay in response. 

I've added rudimentary support for formatting in #731. However, the formatting topic is huge and I'm reluctant to add the rich functionality this PR brings to gspread, especially since I don't use formatting automation myself.

I believe was a very good idea to move this PR into its own package. [gspread-formatting](https://github.com/robin900/gspread-formatting) is great. I've linked the project from the documentation in e77fec6e62a452406192a9382c0a359131a21710.

Thank you for your work. I'm closing the PR.

**Pull request closed without merging**
