### PR TITLE
Added function to create blank spreadsheets

### PR DESCRIPTION
**Pull request by cstarner**
I've added a function to create a blank spreadsheet. Since Google now requires OAuth 2.0, you can use the client session object to communicate with the Drive API, since the auth token will still work, so long as you have initialized the token with the appropriate scope.

### CODE REVIEW

**Comment by burnash** [comment]
Thanks for the pull request. Can you add a test case for this? 

The test suite is in https://github.com/burnash/gspread/blob/master/tests/test.py

**Comment by cstarner** [comment]
Done.

**Comment by imposeren** [comment]
documentation changes are also needed. And note about required oauth2 scope should also be added to docs ('https://www.googleapis.com/auth/drive.file')

**Comment by imposeren** [comment]
And in many cases it's useless without permissions change. For example to make it public:

        perms_url = 'https://www.googleapis.com/drive/v2/files/{0}/permissions'.format(sheet_id)
        perms_data = {'role': 'reader', 'type': 'anyone'}
        self.session.request('POST', perms_url, headers=headers, data=json.dumps(perms_data))

**Comment by NinshuBird** [comment]
403: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "insufficientPermissions",
    "message": "Insufficient Permission"
   }
  ],
  "code": 403,
  "message": "Insufficient Permission"
 }
}

**Comment by imposeren** [comment]
> This function creates the spreadsheet in memory but it doesn't create the spreadsheet in your Google account .

are you sure? I'm already using similar feature in my project and it works:

```python
    def new_spread(self, title, g_client):
        create_url = 'https://www.googleapis.com/drive/v2/files'
        headers = {'Content-Type': 'application/json'}
        data = {'title': title, 'mimeType': 'application/vnd.google-apps.spreadsheet'}
        r = g_client.session.request('POST', create_url, headers=headers, data=json.dumps(data))
        resp = json.loads(r.read().decode('utf-8'))
        sheet_id = resp['id']
        return g_client.open_by_key(sheet_id)

    def make_public(self, file_id, g_client):
        perms_url = 'https://www.googleapis.com/drive/v2/files/{0}/permissions'.format(file_id)
        headers = {'Content-Type': 'application/json'}
        data = {'role': 'reader', 'type': 'anyone'}
        g_client.session.request('POST', perms_url, headers=headers, data=json.dumps(data))

        admin_email = os.environ.get('ADMIN_EMAIL')
        g_client.session.connections = {}
        if admin_email and admin_email.find('@gmail') >= 1:
            data = {'role': 'writer', 'type': 'user', 'value': admin_email}
            g_client.session.request('POST', perms_url, headers=headers, data=json.dumps(data))

    def handle(self, *args, **options):
        self.verbosity = int(options.get('verbosity', 1))
        now = timezone.now()
        json_key = json.load(open(os.path.join(settings.BASE_DIR, 'varying', 'gdrive_oauth.json')))
        scope = ['https://spreadsheets.google.com/feeds', 'https://www.googleapis.com/auth/drive.file']
        credentials = SignedJwtAssertionCredentials(json_key['client_email'], json_key['private_key'], scope)

        g_client = gspread.authorize(credentials)

        # players XP:
        players_spread = self.new_spread('Players XP: ' + unicode(now), g_client)
        self.make_public(players_spread.id, g_client)
```

**Comment by cstarner** [comment]
@imposeren: Thanks for the heads up about the need to change the spreadsheet permissions; I will shortly add on a function to change the permissions. 

@NinshuBird: This function worked properly for me; I would not have tried to submit a pull request without first checking to see if it at least created a spreadsheet. As of right now, this function will create a spreadsheet in the Google Drives base directory; have you tried looking for the spreadsheet there?

**Comment by burnash** [comment]
@cstarner Thanks again for the pull request. The PR is now merged (c4301379c31bf1c2b697a98fb8426f8fad10910b) although for some reason GitHub refuses to acknowledge this. It might be due to manual conflict resolution. I'm closing the PR.

@imposeren thanks for the input about the scope and the permissions.

**Pull request closed without merging**
